#!/usr/bin/env python3

import os
import glob
import shutil
import pandas as pd

from _shell import run_tool


directory = os.path.dirname(os.path.abspath(__file__))


class MMseqs2(object):
  def __init__(self, query, proteome, max_mismatches, method_parameters):
    if max_mismatches == -1:
      max_mismatches = 7

    self.query = query
    self.proteome = proteome
    self.proteome_name = str(proteome).replace('.fasta', '')

    self.max_mismatches = max_mismatches
    self.threads = int(method_parameters.get('threads', 1))
    # Cap on results per query (MMseqs2's --max-seqs). Reads the same 'max_target_seqs'
    # key as BLAST so one --max-target-seqs sweep drives both tools together.
    self.max_seqs = int(method_parameters.get('max_target_seqs', 100000))

    bin_directory = method_parameters['bin_directory']
    self.bin_file = os.path.join(bin_directory, 'mmseqs')

  def __str__(self):
    return 'MMseqs2'

  def preprocesss(self):
    run_tool(f"{self.bin_file} createdb {self.proteome} {self.proteome_name}", 'mmseqs-createdb')
    # --mask 0 here too: the index stores masked residues, so masking must be off at
    # build time as well as search time for the masking-off policy to actually hold.
    run_tool(
      f"{self.bin_file} createindex {self.proteome_name} tmp "
      f"--threads {self.threads} --mask 0",
      'mmseqs-createindex',
    )

  def mmseqs_search(self):
    # Tuned for maximum recall: highest sensitivity, uncap results per query.
    # --mask 0 / --comp-bias-corr 0 mirror DIAMOND's --masking 0 / --comp-based-stats 0.
    # Both default to ON in MMseqs2 and would otherwise suppress the low-complexity
    # queries (COSMIC contains literal homopolymers such as AAAAAAAAA), leaving MMseqs2
    # handicapped relative to the other tools. Every tool runs masking-off so the
    # comparison is symmetric.
    run_tool(
      f"{self.bin_file} easy-search {self.query} {self.proteome_name} "
      f"results.m8 tmp -s 7.5 -e 10000 --max-seqs {self.max_seqs} --threads {self.threads} "
      f"--mask 0 --comp-bias-corr 0 "
      "--format-output \"qseq,taln,theader,mismatch,tstart\"",
      'mmseqs-easy-search',
    )

    all_matches = []
    with open('results.m8', 'r') as file:
      lines = file.readlines()

      for line in lines:
        match = []
        result = line.split('\t')

        for i in range(len(result)):
          if i == 1:
            # aligned target sequence: carries '-' gap chars on indel alignments;
            # stripping them yields the true contiguous match (a no-op when ungapped).
            match.append(result[i].replace('-', ''))
          elif i == 2:
            match.append(result[i].split(' ')[0])
          elif i == 3:
            continue  # skip the max_mismatches column
          elif i == 4:
            match.append(int(result[i].replace('\n', '')))
          else:
            match.append(result[i])

        all_matches.append(match)

    return all_matches


class Benchmarker(MMseqs2):
  def __init__(
    self, benchmark: str, query: str, proteome: str, lengths: list, max_mismatches: int,
    method_parameters: dict
  ):
    self.benchmark = benchmark
    self.query = query
    self.proteome = proteome
    self.lengths = lengths
    self.max_mismatches = max_mismatches
    self.method_parameters = method_parameters

    super().__init__(query, proteome, max_mismatches, method_parameters)

  def __str__(self):
    return 'MMseqs2'

  def preprocess_proteome(self):
    return self.preprocesss()

  def preprocess_query(self):
    raise TypeError(self.__str__() + ' does not preprocess queries.\n')

  def search(self):
    matches = self.mmseqs_search()

    all_matches = []
    for match in matches:
      match = list(match)
      try:  # try taking the UniProt ID - else do nothing
        match[2] = match[2].split('|')[1]
      except IndexError:
        pass
      all_matches.append([str(i) for i in match])

    columns = ['Query Sequence', 'Matched Sequence', 'Protein ID', 'Index start']

    # remove all files generated by MMseqs2, tolerating whatever this version wrote.
    db_dir = os.path.dirname(str(self.proteome))
    for pattern in ['*.source', '*.dbtype', '*.index', '*.idx', '*.lookup', '*_h*']:
      for f in glob.glob(os.path.join(db_dir, pattern)):
        try:
          os.remove(f)
        except OSError:
          pass
    for f in [self.proteome_name, 'results.m8']:
      try:
        os.remove(f)
      except OSError:
        pass
    try:
      shutil.rmtree('tmp')
    except OSError:
      pass

    return pd.DataFrame(all_matches, columns=columns)
